
apiVersion: v1
kind: Service
metadata:
  name: demo-service-api
  labels:
    app: demo-api-app
spec:
  type: NodePort
  selector:
    app: demo-api-app
  ports:
  - port: 88
    targetPort: 8888
    protocol: TCP
    nodePort: 32088
---

apiVersion: v1
kind: Service
metadata:
  name: demo-service-www
  labels:
    app: demo-www-app
spec:
  type: NodePort
  selector:
    app: demo-www-app
  ports:
  - port: 88
    targetPort: 8888
    protocol: TCP
    nodePort: 32089
